# Setup
title:               wkoszolko
tagline:             'wkoszolko.github.io'
description:         ''
url:
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Wojciech Koszołko
  url:               https://wkoszolko.github.io
  email:             w.koszolko@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
